Detour/Include/DetourMath.h, DetourCrowd/Source/DetourCrowd.cpp, DetourCrowd/Source/DetourObstacleAvoidance.cpp
Also changed fabs reference to fabsf, as all callers are passing floats anyway and renamed dtMathFabs to reflect this.
=> Replaced math function macros with inline functions.

DetourCrowd/Source/DetourObstacleAvoidance.cpp
=> Fix as discussed in PR#111

DetourCrowd/Include/DetourCrowd.h
=> Better documentation for a few private fields in dtCrowdAgent

Recast/Include/Recast.h, Recast/Source/RecastRasterization.cpp, RecastDemo/Source/Sample_SoloMesh.cpp, RecastDemo/Source/Sample_TempObstacles.cpp, RecastDemo/Source/Sample_TileMesh.cpp
=> handle the case when allocSpan fails to allocate memory

DetourCrowd/Source/DetourObstacleAvoidance.cpp, RecastDemo/Include/SlideShow.h, RecastDemo/Include/TestCase.h, RecastDemo/Source/ChunkyTriMesh.cpp, RecastDemo/Source/Sample_TempObstacles.cpp, RecastDemo/Source/TestCase.cpp, RecastDemo/Source/main.cpp
Unused variables, signed/unsigned mismatching, and a global variable.  Also changed test case include/exclude flags to unsigned shorts to match their usage,
=> Removed a smattering of compiler warnings

Detour/Include/DetourAlloc.h, Detour/Source/DetourAlloc.cpp, DetourTileCache/Include/DetourTileCacheBuilder.h, Recast/Include/RecastAlloc.h, Recast/Source/RecastAlloc.cpp
This was already partly done by @cexikitin in #65, I'm just finishing it
off in their absence!
Closes #65
=> Use size_t for rcAlloc and dtAlloc

CONTRIBUTING.md
Mikko just mentioned this in #176 and he's spot-on. How's this for wording?
=> Add note to CONTRIBUTING doc to mention screenshots and debug draw

RecastDemo/Contrib/stb_truetype.h
This is just an upgrade to the latest stb_truetype, in order to fix some warnings present in the old version.
No point merging #181 only to delete stb_image straight away! Let's just upgrade stb_truetype, and I'll submit another PR getting rid of stb_image and SlideShow.
=> Update stb_truetype to latest version

Detour/Include/DetourCommon.h, Detour/Source/DetourNavMesh.cpp, Detour/Source/DetourNavMeshBuilder.cpp, Detour/Source/DetourNavMeshQuery.cpp, Recast/Source/RecastMeshDetail.cpp
Yet more warning fixes for a few things - dead assignments throughout the codebase as reported in #93.
Fixes #93.
=> Miscellaneous warning fixes, again

Recast/Include/Recast.h, Recast/Source/Recast.cpp, Tests/Recast/Tests_Recast.cpp
These are by no means complete coverage of the functions they test, but are at least a start.
=> Unit tests for a good number of core Recast functions.

Recast/Source/RecastLayers.cpp
The function now fails if it fails to insert all layers because the
array overflowed. Previously this would silently corrupt the heap.
See discussion in #141.
@memononen Can you review this and comment on whether the bail-out on overflow of layers is ok?
=> Detect all overflows in rcBuildHeightfieldLayers

Detour/Source/DetourNavMeshBuilder.cpp
In U and A shaped terrain it was possible that polygons extruded their
BV-tree nodes significantly. This happened because all points for the
polygon (when excluding the detail mesh) were either on the high-level
terrain, or on the low-level terrain. This fixes the long-standing todo
about this.
As a result of this change, findNearestPoly and queryPolygons should
return more accurate results.
Fix #230
Note that Mikko talks about using "byte per bbox extents" in the todo.
I am not quite sure I understand that comment - can you explain what you
meant @memononen?
=> Take detail mesh into account for creating BV-tree

Recast/Source/RecastMesh.cpp
This is so trivial I'll merge it myself :)
=> Fix multiline comment warning

RecastDemo/Source/Sample_TempObstacles.cpp
I've tested saving and loading on Windows, and that it builds on Linux. Seems safe and will shut up GCC's warning about ignored return values from `fread`. I chucked in a memory leak fix while I was in the function.
=> Fix some warnings by adding error checking to Sample_TempObstacles::loadAll

RecastDemo/Include/Sample.h, RecastDemo/Include/Sample_TempObstacles.h, RecastDemo/Source/Sample.cpp, RecastDemo/Source/Sample_SoloMesh.cpp, RecastDemo/Source/Sample_TempObstacles.cpp, RecastDemo/Source/Sample_TileMesh.cpp
I wanted to see the effect of the various filtering options available, so I added toggles for each of them.
=> Add toggles for heightfield filtering

Detour/Include/DetourAssert.h, Detour/Source/DetourAssert.cpp, Recast/Include/RecastAssert.h, Recast/Source/RecastAssert.cpp
Implemented the ability to set custom function to be called in case of assertion failure.
This functionality is similar to custom allocation functions.
=> Assertion failure custom function

Detour/Include/DetourConfig.h, Detour/Include/DetourNavMesh.h, Detour/Include/DetourNavMeshQuery.h, Detour/Include/DetourNode.h, Recast/Include/Recast.h, Recast/Include/RecastConfig.h
I am starting some improvements on R&D. To begin with, I want to do some of the cleanup that @hymerman has suggested earlier by moving configs into their own files.
If I missed any config types/variables/values please let me know!
=> Add RecastConfig.h and DetourConfig.h

Detour/Include/DetourNavMesh.h, Detour/Include/DetourNavMeshQuery.h, Detour/Source/DetourNavMesh.cpp, Detour/Source/DetourNavMeshQuery.cpp, DetourCrowd/Include/DetourCrowd.h, DetourCrowd/Source/DetourCrowd.cpp, DetourCrowd/Source/DetourPathCorridor.cpp, DetourTileCache/Include/DetourTileCache.h, DetourTileCache/Include/DetourTileCacheBuilder.h, DetourTileCache/Source/DetourTileCache.cpp, DetourTileCache/Source/DetourTileCacheBuilder.cpp, RecastDemo/Include/Sample_Debug.h, RecastDemo/Source/ConvexVolumeTool.cpp, RecastDemo/Source/CrowdTool.cpp, RecastDemo/Source/NavMeshPruneTool.cpp, RecastDemo/Source/Sample_Debug.cpp
And left one duplicate method to maintain backwards compatibility.
=> Renamed all instances of 'extents' to 'halfExtents'

RecastDemo/Source/SampleInterfaces.cpp
Time val was loosing precision.
=> Liam karl mitchell patch 289

RecastDemo/Source/MeshLoaderObj.cpp
Fix #283 in a similar manner as #258
=> Mark a fall-through with a comment

README.md
=> doc: just fix typo SDl -> SDL

README.md
We shouldn't leave such a shocking typo on such a nice description, now should we? ;)
This PR doesn't constitute an endorsement for passive voice, though.
=> Fix for typo in README

Recast/Source/RecastMeshDetail.cpp
=> Improve triangulateHull to start from an ear with shortest perimeter

RecastDemo/Source/CrowdTool.cpp
=> Removed unnecessary comment

Recast/Include/RecastAlloc.h, RecastDemo/Include/Sample_TempObstacles.h, RecastDemo/Source/Sample_TempObstacles.cpp, RecastDemo/Source/imgui.cpp, RecastDemo/premake5.lua, Tests/catch.hpp, appveyor.yml
=> Allow 64 bit windows builds

DebugUtils/CMakeLists.txt, DetourCrowd/CMakeLists.txt, DetourTileCache/CMakeLists.txt
=> Add dependencies between libraries to allow linker to resolve symbols when build dynamic libraries

CMakeLists.txt, DebugUtils/CMakeLists.txt, Detour/CMakeLists.txt, DetourCrowd/CMakeLists.txt, DetourTileCache/CMakeLists.txt, Recast/CMakeLists.txt, Tests/CMakeLists.txt
To make this easier to package
=> Several fixes for make install

RecastDemo/Include/TestCase.h, RecastDemo/Source/TestCase.cpp
=> Fix compiler error due to memset on type with non-trivial constructors

.travis.yml
use defaults where possible, simplify .travis.yml and fix macos builds while we are at it
/cc @glebm
=> Fix MacOS builds on Travis

Detour/Source/DetourNavMesh.cpp
=> Fix rounding error due to precision loss after optimization.

Docs/Conceptual/FAQ.md
From http://digestingduck.blogspot.com/2009/08/recast-settings-uncovered.html with some editing for clarity and readability :) 
Fixes #553
=> Added configuration protips from Mikko's blog to a FAQ

Recast/Source/RecastContour.cpp
=> fixed a typo (countour -> contour)

CMakeLists.txt, Detour/CMakeLists.txt
Same thing as #627, but for DT_VIRTUAL_QUERYFILTER.
=> Add a CMake option to use dynamic dispatch for dtQueryFilter in Detour.

Detour/Include/DetourNavMesh.h
Fixes a small typo in DetourNavMesh.h.
=> Fix typo in DetourNavMesh.h

Recast/Source/RecastRasterization.cpp
* Rename hf -> heightfield to be consistent
* Removed unused include
=> Some quick cleanup in RecastRasterization.cpp

Recast/Source/RecastMesh.cpp
There is no need for ELSE after an IF statement that always ends with a return.
=> Minor refactor in RecastMesh.cpp

Docs/Roadmap.md, Doxyfile, README.md
Added logo, updated doxyfile, fixed alignment of top-level readme, and changed the logo url to an s3-hosted file since github has restrictions that prevent it from loading on recastnav.com
=> Improved doxygen output

Recast/Include/Recast.h, Recast/Source/RecastFilter.cpp, Tests/Recast/Tests_RecastFilter.cpp
This mostly just changes variable names and adds some comments to make the code more clear.
It also has a few small fixup changes to the unit tests.
=> Cleanup filter code and improved documentation
