DetourCrowd/Source/DetourCrowd.cpp
Otherwise, if velocity was non zero at time resetMoveTarget is called the agent would continue to move indefinitely at that velocity (a straight line) which was not the intended behaviour.
As discussed in https://groups.google.com/forum/#!topic/recastnavigation/QoLNGz5o6e8
=> reset agent desired velocity in resetMoveTarget

Detour/Include/DetourNavMeshQuery.h, Detour/Source/DetourNavMeshQuery.cpp
This makes it simpler to investigate exactly what is blocking a ray - for example, if an agent cannot move onto a polygon due to QueryFilter flags, then this provides a way for the agent to find out which flags it needs to have and to perform a state change which alters its movement flags.
=> Include hit edge index in dtRaycastHit.

.travis.yml, README.md, RecastDemo/Contrib/readme-sdl.txt, RecastDemo/premake5.lua, appveyor.yml
Build scripts download SDL, download (or build) premake5, generate projects, then build, in several configurations and platforms
Project now builds with premake5 instead of premake4 to allow VS2015 project generation
Tweaked SDL directory dependency to work better with CI
Update README
This replaces my PR #89 - I wanted to create one new squashed commit rather than leave the messy history with checked in binaries.
=> Add AppVeyor and Travis CI build scripts

Recast/Source/RecastMeshDetail.cpp, Recast/Source/RecastRegion.cpp
Comment unused parameters to avoid build warnings when Recast and Detour and built with /W4 on windows or -Wunused-parameter on gcc/clang
=> Fix 2 "unused parameter" build warnings

DetourTileCache/Source/DetourTileCache.cpp
When a temp obstacle completely covers a tile, the old mesh tile is not removed.
=> Old mesh tile not removed when new tile is empty (temp obstacles)

Detour/Source/DetourNavMeshQuery.cpp
When the same point is used as center and as nearestPt, the function
would override center and give wrong results.
Fix #118
=> Use intermediate variable for nearest point in findNearestPoly

Detour/Source/DetourNavMeshQuery.cpp
=> findNearestPoly now fails when nearestRef is null, and only assigns it when the function succeeds

Detour/Include/DetourNavMesh.h, Detour/Source/DetourNavMesh.cpp
(As discussed in #113)
External links representing off mesh connections between layers in the
same tile location would not be correctly removed. These links had
side = 0xff which were skipped during tile removal under the assumption
that these links were internal.
Also correct some comments in the same place.
Fix #113
=> Correctly remove off mesh links to other layers

Detour/Include/DetourNavMesh.h
"Options for dtNavMeshQuery::FindPath" is not correct, the option is used in SlicedFindPath only
DT_FINDPATH_LOW_QUALITY_FAR is not used anywhere
I would also add, that even though raycast considers costs, does so not very well :-(
=> Updated dtFindPathOptions description and options

RecastDemo/premake5.lua
Just a small fix for when the solution/bin path contains spaces. This was the only thing
preventing me from running it directly after premake generation.
=> Ensure SDL2.dll is copied for paths with spaces

RecastDemo/Include/ChunkyTriMesh.h, RecastDemo/Include/Filelist.h, RecastDemo/Include/SlideShow.h, RecastDemo/Source/Filelist.cpp, RecastDemo/Source/SlideShow.cpp, RecastDemo/Source/main.cpp
The goals of the demo project (as I see it at least) are to:
1.  Showcase Recast and Detour's capabilities and flexibility
2.  Provide a clear example of how to correctly interact with the Recast and Detour API's
3.  Provide a flexible base on which people can build proprietary tools.
The demo project doesn't have the same dependency restrictions as Detour and Recast, and benefits more from clarity and flexibility.  I feel like using STL is an improvement in both these areas over hand-rolled collections and c-style strings.  To be clear, I feel this only applies to the demo project, and not Recast and Detour as a whole.
I'd love to hear people's input on this, especially if they disagree.
=> Replaced FileList class with std::vector<std::string>

RecastDemo/Include/PerfTimer.h, RecastDemo/Include/SampleInterfaces.h, RecastDemo/Source/CrowdTool.cpp, RecastDemo/Source/PerfTimer.cpp, RecastDemo/Source/SampleInterfaces.cpp, RecastDemo/Source/TestCase.cpp
The demo relied on the build context returning accumulated times in
microseconds. On Windows this was using QueryPerformanceCounter directly
which has a higher resolution, thus returning wrong measured times. We
now report the accumulated times in microseconds on all platforms.
=> Fix time measuring on Windows

Detour/Source/DetourNavMesh.cpp
dtNavMesh needs exclusive access to the data passed to addTile since it
will make dynamic changes to this at runtime. For that reason the data
should not be reused until the tile has been removed from the nav mesh
again.
Fix #149
=> Add documentation about data to addTile

Recast/Source/RecastLayers.cpp
This fix is the fix Mikko suggested in #30. However, I don't completely understand
the code here. As far as I can see, this code tries to identify which regions should be merged into what will finally become the layers. @memononen, can you try explaining why it's ok that we do not collect all of these regions? Would it not be better to expand the array to be able to collect all the neighbours? Or will this situation just introduce a few more layers, which is probably ok?
The collecting could overflow the neighbours array due to a missing boundary
check.
Fix #30
=> Fix heap corruption when collecting region layers

Recast/Include/Recast.h, Recast/Include/RecastAlloc.h, Recast/Source/RecastAlloc.cpp, Recast/Source/RecastMesh.cpp, Recast/Source/RecastMeshDetail.cpp
Use flood fill for potentially overlapping polys
This changes the detail sampling to find height data by using the flood
fill method for polygons that were merged because of a border vertex
removal. This could potentially cause overlapping polygons to receive
the same region IDs which would later make the fast-path sampling in
getHeightData sample the wrong heights.
Also includes optimizations for this path and getHeightData itself.
Previously the seeding was responsible for 25% of the total time spent
in getHeightData in these cases. We now use the direction and prune the
nodes when we move towards the center cell, instead of doing a
full-blown DFS. This makes the overhead of seedArrayWithPolyCenter
virtually nonexistent (~2% according to profiling).
In my tests this new path was only …
=> Use flood fill for potentially overlapping polys

Recast/Include/Recast.h, Recast/Source/RecastContour.cpp, Recast/Source/RecastMesh.cpp, Recast/Source/RecastMeshDetail.cpp
When the detail mesh sampling sees an unset height it previously tried
to recover by looking for heights of neighbors. When the heightfield was
not eroded this recovery would fail since the contour simplification
could mean that the nearest valid cell was further away than a neighbor.
We now walk adjacent cells in a spiral to find a height and do this
depending on the max simplification error.
Fix #153
=> Increase recover radius for unsampled heights

README.md
It appears that BitDeli is defunct; their website has had a banner about a change in the GitHub API for a long time, which is a dead link to a blog article, and none of the example stats have been updated for years. Let's just remove it!
=> Remove BitDeli badge from README.md

DetourTileCache/Source/DetourTileCache.cpp
There is a class and a struct called BuildContext in two different files,
one .h and one .cpp. Depending on how the user structures their program,
it's possible that this would cause a compile or link error, as seems to
have happened in #44. I've just renamed the struct to get around this.
Fixes #44
=> Fix possible compile/link error with multiple BuildContext definitions

README.md
The readme was looking lonely after the BitDeli badge was taken away. Here are some nice badges to replace it, which also helpfully show how active a project this has become! They show recent average time to close issues and PRs.
=> Add Issue Stats badges to README.md

.gitignore, RecastDemo/Include/Filelist.h, RecastDemo/Include/InputGeom.h, RecastDemo/Include/MeshLoaderObj.h, RecastDemo/Include/Sample.h, RecastDemo/Include/Sample_TileMesh.h, RecastDemo/Include/TestCase.h, RecastDemo/Source/Filelist.cpp, RecastDemo/Source/InputGeom.cpp, RecastDemo/Source/MeshLoaderObj.cpp, RecastDemo/Source/Sample.cpp, RecastDemo/Source/Sample_SoloMesh.cpp, RecastDemo/Source/Sample_TempObstacles.cpp, RecastDemo/Source/Sample_TileMesh.cpp, RecastDemo/Source/TestCase.cpp, RecastDemo/Source/main.cpp
This adds the ability for geometry sets to store build settings that can
be automatically applied when they are loaded. This should allow sharing
of .gset files to demonstrate problems with certain settings on certain
files. It also allows people to diagnose problems more easily by being
able to dump their own triangle meshes and settings and load them in the
demo, with all of its visualization options. .gset files can be created
from the current mesh and settings by pressing the 9 key, which will
generate it in the same folder as the input mesh.
Also converts more of the demo to use STL.
The reason I introduced `navMeshBMin` and `navMeshBMax` is because it allows people
to use the demo to diagnose problems more easily. I (and I'm sure Mikko) have noticed a general
trend in visualizers …
=> Add settings storage to geometry sets

Detour/Include/DetourNavMeshQuery.h, Detour/Source/DetourNavMeshQuery.cpp
This adds a version of queryPolygon that takes an interface which is
passed batches of polygons in the search area. This new API is then used
from the old queryPolygons to collect polygons, and from findNearestRef
to find the nearest poly in an arbitrarily sized area. Previously
findNearestPoly had an arbitrary poly limit of 128 which could cause it
to return potentially wrong results.
Fix #107
I was concerned about the impact of this since it adds some virtual overhead
and additional copying to `queryPolygons`. I've added some benchmarks below.
At least on my CPU the overhead is not extremely high, though it is still around 10%
at large extents. The comments at the top of `DetourNavMeshQuery.h` say that
virtual dispatch is expensive on certain platforms, so the performance regression
may …
=> Add API to query polygons in batches

Detour/Source/DetourNavMeshQuery.cpp, RecastDemo/Source/imgui.cpp
Fix three warnings added in fc5df2c, and increase the text pool size in
the demo. This would frequently be overflowed, even just by building
with the default settings and expanding the log.
=> Fix warnings and increase demo text pool size

RecastDemo/Source/Filelist.cpp
As identified by @b-desconocido, `_findfirst` has a return type of `intptr_t`;
this was previously being truncated to long, resulting in a crash on 64 bit Windows.
Fix #185
=> Fix Win64 when populating input file list

DetourCrowd/Source/DetourObstacleAvoidance.cpp, DetourCrowd/Source/DetourProximityGrid.cpp, DetourTileCache/Source/DetourTileCacheBuilder.cpp, Recast/Include/RecastAlloc.h, RecastDemo/Include/ChunkyTriMesh.h, RecastDemo/Include/CrowdTool.h, RecastDemo/Include/TestCase.h, RecastDemo/Source/NavMeshPruneTool.cpp, RecastDemo/Source/NavMeshTesterTool.cpp
Just a few random fixes for warnings reported by either Clang, Coverity or ReSharper C++.
=> Miscellaneous warning fixes

Detour/Source/DetourNavMesh.cpp, Detour/Source/DetourNavMeshQuery.cpp, DetourTileCache/Source/DetourTileCache.cpp, Recast/Source/RecastMeshDetail.cpp, Recast/Source/RecastRegion.cpp, RecastDemo/Contrib/stb_truetype.h, RecastDemo/Source/InputGeom.cpp, RecastDemo/Source/MeshLoaderObj.cpp, RecastDemo/Source/SampleInterfaces.cpp, RecastDemo/Source/Sample_TempObstacles.cpp, RecastDemo/Source/Sample_TileMesh.cpp, RecastDemo/Source/TestCase.cpp, RecastDemo/Source/imguiRenderGL.cpp
Yet more warning fixes, for a smattering of issues found using either Coverity Scan, clang's scan-build or ReSharper C++. Each fix is in its own commit so the best way to see what's fixed is to read the individual commit messages.
=> Miscellaneous warning fixes, part 3

Recast/Include/Recast.h, Recast/Source/Recast.cpp
This adds a default constructor and a destructor to the rcHeightfield struct, and disables the default copy constructor and copy assignment operator.  
While implementing unit tests that use rcHeightfield, there was an observation that rcHeightfield's that aren't made through `rcAllocHeightfield()` and subsequently free'd thorugh `rcFreeHeightfield()` leak memory.  This restricted all rcHeightfield allocations to the heap.  In addition to being an unnecessary constraint that could have adverse performance impacts, it also was causing memory leaks in test cases that couldn't call `rcFreeHeightfield()`.
This shouldn't have any measurable impact on performance, as heightfield's aren't allocated nearly as often as other objects, and the compiler should do a good job of inlining calls to the …
=> Added Constructor and Destructor to rcHeightfield

Detour/Include/DetourNavMeshBuilder.h, DetourCrowd/Include/DetourCrowd.h
Technically newlines are required at the end of files in C++03
Fixes #198
=> Added eof newlines.

RecastDemo/Source/Sample_TempObstacles.cpp
Caused by #158.
Can be reproduced by selecting the "Temp Obstacles" sample and pressing build multiple times. Memory will leak because it uses the alloc function from dtTileCacheAlloc and the free function from LinearAllocator (which is empty).
Another improvement would be to change dtTileCacheAlloc to an abstract empty implementation, similar to dtTileCacheCompressor. Existing usage of dtTileCacheAlloc would break though.
=> Fix memory leak in LinearAllocator used by Sample_TempObstacles

DetourTileCache/Include/DetourTileCache.h, DetourTileCache/Source/DetourTileCache.cpp
This changes dtTileCache::update to add an optional parameter that
indicates whether the tile cache is up to date. This is useful to
determine whether calling the function again would do anything.
=> Add upToDate param for dtTileCache::update

Detour/Source/DetourNavMesh.cpp
When creating the tile's links, offmesh connections inside the tile
were added twice, leading to the array of links being full and not
being able to store the links computed after (portals between
tiles).
Google group discussion : 
https://groups.google.com/forum/#!msg/recastnavigation/l-_Mk1O4I04/PWE0dGSKBAAJ
=> Fixed a links issue due to offmesh connections

Detour/Source/DetourNavMeshQuery.cpp
This changes the Dijkstra searches in findPolysAroundCircle and
findPolysAroundShape to append the results when we visit nodes in the
main loop. The algorithm guarantees that we will never visit them again
after this, so at this point we are guaranteed that we cannot find a
better path.
Previously results would be appended the first time we saw a polygon
which meant later improvements on the paths to those polygons would not
be reflected in the results.
Fix #204
=> Append results correctly in Dijkstra searches

Detour/Source/DetourNavMeshQuery.cpp
`findPolysAroundCircle` and `findPolysAroundShape` were only using distances
to compute the costs. This was inconsistent with other APIs that
performed cost-based searches and accepted filters as parameters.
This is a small breaking change, but the previous behavior is easy to get simply by passing a filter with all area costs as 1. The new behavior is probably what most people would expect from the function once they realize it is a Dijkstra search, so I think we should take this breaking change.
=> Take area costs into account in Dijkstra searches

Detour/Include/DetourNavMeshQuery.h, Detour/Source/DetourNavMeshQuery.cpp
This adds a method to dtNavMeshQuery that allows users to retrieve paths
from the nodes explored by the previous search. This is especially
useful after Dijkstra searches to retrieve arbitrary paths inside the
explored circle.
As expected the removal of the fast path in `findPath` hurts its execution time pretty badly for paths of length 1:
| Resulting path length | Number of nodes | New time per query | Old time per query |
| --------------------- | --------------- | ------------------ | ------------------ |
| 1 | 32 | 0.042376 µs | 0.017040 µs |
| 1 | 64 | 0.045196 µs | 0.014216 µs |
| 1 | 128 | 0.044628 µs | 0.015892 µs |
| 1 | 256 | 0.052404 µs | 0.014280 µs |
| 1 | 512 | 0.058444 µs | 0.014332 µs |
| 1 | 1024 | 0.058892 µs | 0.015176 µs |
| 1 | 2048 | 0.064912 µs | 0.014220 µs |
| 1 …
=> Add getPathFromSearch function

DetourTileCache/Source/DetourTileCacheBuilder.cpp
I've opted not to introduce a RAII class here as `data` is output anyway, so it would mostly benefit for `buffer`; but this file only uses this pattern in this one place, so I don't think it would be worth it.
=> Fix a possible memory leak in dtBuildTileCacheLayer

Detour/Include/DetourNavMeshQuery.h
=> Fix for Struct 'dtNode' was previously declared as a class

RecastDemo/Source/NavMeshPruneTool.cpp
The start poly would not be pruned if it was the only poly on the
island.
Fix #216
While I was here I've also taken the liberty of replacing the custom dynamic array with `std::vector`.
=> Prune tool start fix

Recast/Source/RecastAlloc.cpp
Fix #170 
Initially I wanted to do better error checking and handle the allocation failures
by returning errors from the APIs. However, there are very many usages and
since we do not use exceptions in the core this approach significantly worsens the code.
Since the `rcIntArray` usages are generally for small arrays I think just an assertion is fine,
while we can let the Recast fail if the bigger allocations fail.
=> Add an assertion for alloc in rcIntArray::doResize

.editorconfig
This file specifies the indentation settings used in R&D. This should help keep the code base consistent.
It is very useful when you are switching between multiple projects with different indentations,
or when you have multiple developers with different environment.
Some IDEs support parsing this file format out of the box, and otherwise there exist lightweight plugins that parses the file format and applies the settings for virtually all IDEs.
See http://editorconfig.org/.
=> Add .editorconfig with tabs

DetourTileCache/Include/DetourTileCache.h, DetourTileCache/Include/DetourTileCacheBuilder.h, DetourTileCache/Source/DetourTileCache.cpp, DetourTileCache/Source/DetourTileCacheBuilder.cpp
The current dtTileCache supports cylindrical shaped obstacles, but this tends to be a very limiting obstacle shape that doesn't fit many use cases very well. An AABB is a bit more flexible and doesn't take much to implement.
It would be nice to also support extruded convex polys like recast does, but this is a good start.
=> Add support for AABB shaped obstacles to dtTileCache

Detour/Source/DetourNavMeshQuery.cpp
findPath was unconditionally overriding the status it used to indicate
DT_OUT_OF_NODES for later. Restore this behavior so it properly can
return this failure flag.
Fix #221
=> Fix findPath to return DT_OUT_OF_NODES correctly

Detour/Source/DetourNavMesh.cpp, Detour/Source/DetourNavMeshQuery.cpp
When a point is outside the polygon being queried in
dtNavMesh::closestPointOnPoly and dtNavMeshQuery::closestPoinOnPoly,
Detour will interpolate along one of the edges to find the closest point
on the poly. However, Detour did not properly use the interpolated point
to find the correct height according to the detail mesh.
Fix #227
=> Properly use detail mesh from closestPointOnPoly

Tests/catch.hpp
Currently there are loads of warnings in Catch code on Travis. This kind of thing:
../../../Tests/Recast/Tests_Recast.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
../../../Tests/Recast/Tests_Recast.cpp:12:3: warning: suggest parentheses around comparison in operand of ‘==’ [-Wparentheses]
../../../Tests/Recast/Tests_Recast.cpp:13:3: warning: suggest parentheses around comparison in operand of ‘==’ [-Wparentheses]
I wondered if upgrading would fix them, but apparently not - no harm in taking the update anyway though I guess?
=> Upgrade Catch to 1.6.0

RecastDemo/premake5.lua
Once #245 is merged, this should pass. It'll be nice to have warnings as errors for one CI platform!
It'll be much harder to do with AppVeyor since on Windows we get a ton of warnings about exception handling. Not sure how to tackle that for now.
=> Set warnings as errors on Linux

RecastDemo/Source/Sample.cpp
I was a bit too fast to merge #254 before checking how the colors actually look.
Turns out the new default color changed significantly; change it back to the old original to retain that look.
=> Change back to previous default color

DetourTileCache/Include/DetourTileCache.h, DetourTileCache/Include/DetourTileCacheBuilder.h, DetourTileCache/Source/DetourTileCache.cpp, DetourTileCache/Source/DetourTileCacheBuilder.cpp
Added option to add rotated Box obstacle to TileCache (without messing with the existing box).
Very useful when you have a obstacle with a big difference in x to z ratio and that could be rotated (not aligned), like a wall.
=> Added option to add rotated Box obstacle to TileCache.

RecastDemo/Contrib/fastlz/fastlz.c, RecastDemo/premake5.lua
The change to fastlz.c could also be implemented via "/wd4244" appropriately placed in premake5.lua
=> Suppress warnings when compiling for VS2015

Detour/Source/DetourNavMeshQuery.cpp
The normal returned by findWallDistance() isn't really a normal, it's just a normalized vector from the hit point to the source point. The hit point is already returned by this function, and the source point was passed in, so it's easy for users to calculate this themselves if they want.
So, instead, return the bitangent to the actual wall itself, as it's more useful.
=> Improve findWallDistance()'s returned normal

RecastDemo/Source/Filelist.cpp
The previous code can not read the .gset file, because of strlen(.gset) > 4 . when strlen(ext) > 4 strncmp(current->d_name + len - 4, ext.c_str(), 4) == 0 is aways false
=> fixed load .gset file error

RecastDemo/Include/Sample.h, RecastDemo/Include/Sample_SoloMesh.h, RecastDemo/Source/InputGeom.cpp, RecastDemo/Source/Sample.cpp, RecastDemo/Source/Sample_SoloMesh.cpp, RecastDemo/Source/Sample_TileMesh.cpp, RecastDemo/Source/TestCase.cpp
- Solo mesh sample is serialized/unserialized with the same format as a **tiled mesh**. It's just a tiled mesh with an unique tile. That means a solo mesh binary is compatible is a tiled mesh loader.
- NavMesh is saved to/loaded from `solo_navmesh.bin` binary file.
- Add and connect the corresponding 'Save/Load' GUI elements.
I took the liberty to not speak with anybody here first about this feature because I already had it implemented. I'm going forward with my [Go port of Detour and Recast](https://github.com/aurelien-rainone/go-detour), that does not support tiled mesh for now. As part of the test suite I was needing a way to save and load solo meshes from the gui, for I'm comparing the binaries produced in Go with the ones from the original library.
=> RecastDemo: add Load & Save buttons for SoloMesh Sample

Recast/Source/RecastRegion.cpp
To avoid uninitialized value when borderSize <= 0.
=> Unconditionally initialize rcCompactHeightfield borderSize

Detour/Include/DetourStatus.h, Detour/Source/DetourNavMesh.cpp
Failure because the tile coordinate is already occupied is the only failure that does not specify more information.
=> Provide better feedback when dtNavMesh::addTile fails due to a tile already being present at a given x,y

Recast/Source/RecastRegion.cpp
rcBuildRegions uses dstReg and dstDist as scratch space. Currently, it copies src* -> dst* on each iteration of the inner loop of expandRegions. This is a costly operation; on a sampled map, it copies 16Mbytes of data, when only ~6kbytes are accessed. We get rid of dst*, and modify expandRegions to keep track of deltas and apply them at the end of each iteration.
This has reduced runtime of the Recast portion of my build pipeline by 70% (!). memcpy() no longer appears in sampled profiles at all.
=> Remove redundant copying in rcBuildRegions.

DetourTileCache/Source/DetourTileCacheBuilder.cpp
In function `dtDecompressTileCacheLayer` buffer is allocated using a call to `dtTileCacheAlloc::alloc` (`DetourTileCacheBuilder.cpp`. line 2181). But if call to `comp->decompress` below fails, `dtFree` is used instead to deallocate the memory (line 2199, which this pull request fixes).
This happens to work for most of the users, because default implementation of `dtTileCacheAlloc::free` calls `dtFree` itself. But it breaks in rare circumstances when you use custom memory allocation *and* decompression fails.
This request fixes that.
=> Call proper memory deallocation function in `dtDecompressTileCacheLayer`.

Recast/Include/RecastAlloc.h, Recast/Source/RecastRegion.cpp, Tests/Recast/Tests_Recast.cpp
Also updates rcVector::clear() to not require the contained type to be default-constructible.
=> Switch expandRegions to using a rcTempVector of structs rather than a blob of ints.

Recast/Include/Recast.h, Recast/Include/RecastAlloc.h, Recast/Source/Recast.cpp
The intention is to use these to move construction logic out of rcAllocateFooObject/rcFreeFooObject and into constructors/destructors, giving users flexibility in how objects are allocated. In particular, this allows stack allocation.
Turns rcAllocateCompactHeightfield into a wrapper around rcNew as a demo. If accepted, PR's for other user objects to follow.
=> Add rcNew/rcDelete, template functions that allocate/deallocate objects using rcAlloc/rcFree.

.editorconfig, .travis.yml, Recast/Include/RecastAlloc.h, RecastDemo/CMakeLists.txt, RecastDemo/Source/Sample_TileMesh.cpp, RecastDemo/premake5.lua, Tests/Detour/Tests_Detour.cpp, appveyor.yml
Adds Clang and VS2017 to CI, and ensures that they are treating warnings as errors. Also fixes the new warnings that cause build break, including #334.
=> Add Clang and VS2017 to CI and fix warnings

DebugUtils/CMakeLists.txt, Detour/CMakeLists.txt, DetourCrowd/CMakeLists.txt, DetourTileCache/CMakeLists.txt, Recast/CMakeLists.txt
* When use `add_subdirectory` it is no more required to say cmake where to find include directories. 
* Allow to use cmake namespace `RecastNavigation` to link libraries. Ex:
```cmake
target_link_libraries(myapp
RecastNavigation::DebugUtils
RecastNavigation::Detour
RecastNavigation::Recast
)
```
=> Allow to use recastnavigation by find_package and add_subdirectory

RecastDemo/premake5.lua
Previously this was relative to the output file. This works around a
premake5 bug (https://github.com/premake/premake-core/issues/1186) and as a bonus makes it easier to support out-of-source builds with premake.
=> Use SDL2.dll path relative to script file

Detour/Source/DetourCommon.cpp
dot00 == v0[0] * v0[0] + v0[2] * v0[2]
...
Denom  = dot00 * dot11 - dot01 * dot01
= (v0[0] * v0[0] + v0[2] * v0[2]) * (v1[0] * v1[0] + v1[2] * v1[2]) - (v0[0] * v1[0] + v0[2] * v1[2]) * (v0[0] * v1[0] + v0[2] * v1[2])
= (v0[0] * v1[2] - v0[2] * v1[0]) * (v0[0] * v1[2] - v1[0] * v0[2])
...
Both u and v have (v0[0] * v1[2] - v1[0] * v0[2]), so we can simplify them.
This optimization can also keep more precision by reduce multiplication.
=> optimize dtClosestHeightPointTriangle

.travis.yml, RecastDemo/CMakeLists.txt
This gives Recastnavigation coverage in the following areas:
- MacOS (Xcode)
- Ubuntu Xenial (GCC-5)
- Ubuntu Xenial (GCC-8)
- Ubuntu Xenial (Clang-7 w/ Static Analysis)
- Coverity Scan (preparation work, not yet turned on)
All of this is done via CMake. I still need to add another build that uses premake5 so that there is coverage there as well.
=> Use Travis-CI Matrix to add more type of builds

Detour/Include/DetourCommon.h, Detour/Include/DetourMath.h, Detour/Source/DetourNavMeshQuery.cpp
Validate input values more consistently and completely, including that points are finite.
This would have saved everyone some time in #343/#373.
=> Add consistent input validation to dtNavMeshQuery

RecastDemo/premake5.lua
Using premake5 as described in the README it is currently not possible to compile the _RecastDemo_ under gcc8. Because warnings are treated as errors due to the "-Werror" compiler flag, false positive warnings cause the compilation to fail.
This commit adds appropriate no-error exception flags in the lua script and allows for a successful build under gcc8. Fixes #380.
It is possible to build the complete project using the main cmake file without these errors!
5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux
gcc version 8.3.0
`../../../Detour/Source/DetourNavMesh.cpp: In member function ‘dtStatus dtNavMesh::init(const dtNavMeshParams*)’:
../../../Detour/Source/DetourNavMesh.cpp:243:50: error: ‘void* memset(void*, int, size_t)’ clearing an object of type …
=> Permit false positive compile errors (gcc8)

Recast/Source/RecastContour.cpp
On some architectures (e.g. ARM), char is unsigned, so winding should be explicitly defined as signed char.
I grepped through the source code, and there doesn't seem to be anywhere else where this is needed.
=> Explicitly define winding as being signed

README.md
The binary has to be run from the bin directory, otherwise the DroidSans font can't be found and shows the error "Could not init GUI renderer.":
https://github.com/recastnavigation/recastnavigation/blob/master/RecastDemo/Source/main.cpp#L129
=> Updates the README instructions for linux

DebugUtils/CMakeLists.txt, Detour/CMakeLists.txt, DetourCrowd/CMakeLists.txt, DetourTileCache/CMakeLists.txt, Recast/CMakeLists.txt
Two changes that make life easier when using the _Visual Studio_ and _nmake_ generators in CMake:
1. When compiling both Release/Debug (e.g. as a batch build inside Visual Studio), it no longer overwrites libraries .lib files. Instead, it creates distinct ones for Release (the same as before), while it adds the `-d` postfix for Debug configuration.
2. Exports PDB files alongside the libraries in Debug mode. This makes it possible that dependent projects have Debug symbols for Recast/Detour available, and avoids linker warnings for missing debug symbols.
Both changes should have no effects when the Microsoft compiler is not used.
=> Improve debug builds for MSVC

CMakeLists.txt, DebugUtils/CMakeLists.txt, Detour/CMakeLists.txt, DetourCrowd/CMakeLists.txt, DetourTileCache/CMakeLists.txt, Recast/CMakeLists.txt
- Export symbols with MSVC
- Delete `RECASTNAVIGATION_STATIC` option, [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) is better
- Install shared runtime library in `bin` folder
=> Fix shared library build

DetourCrowd/Source/DetourCrowd.cpp
Fix for #308 .
The upper limit of the index of `agents` cannot be `m_maxAgents`. So I change it to `nagents`. So the index of `m_agentAnims` shoud be consistent with where it is set in line 1153.
=> fix an index error in DetourCrowd.cpp

Detour/Include/DetourNavMesh.h, Detour/Source/DetourNavMesh.cpp
When adding a tile to a NavMesh, ensure that the number of polygons in that tile fit in the poly ID address space.
I'm not sure if this should be done on the bits (logarithmic) level only, or if it were better if the absolute number of polygons (i.e. `dtNavMeshParams::maxPolys`) should be stored in `DetourNavMesh` and validated. However, this may be a bit harder, since we would need to sum the polygon count for each tile.
Generally, it's not very clear from the documentation how `maxPolys` is used.
=> Validate constraint: #polygons per tile

Detour/Include/DetourNavMeshQuery.h, Detour/Source/DetourNavMeshQuery.cpp
The current API `dtNavMeshQuery::findNearerestPoly()` does not allow the caller to get information about:
* whether `center` is actually _on_ a polygon
* what is the distance to the polygon (even if it's _on_ one, this can be vertical distance).
Of course it would be possible for the caller to compute these after the call, however `findNearestPoly()` has the information readily available.
I simply added an overload and didn't de-duplicate code, please let me know if you think such an API makes sense, and what would be the preferred way.
=> Poly query API: expose distance and isOverPoly

Recast/Include/RecastAlloc.h, Recast/Source/RecastContour.cpp, Recast/Source/RecastMeshDetail.cpp, Recast/Source/RecastRegion.cpp
When profiling recast (as part of openmw), I found a large amount of
time in RecastMeshDetail is spent in reallocing the same vector.
This is because the `resize` method always realloc'd on grow.
Fixes this by only reallocing when needed.
Comparison for `push3` before/after second commit (Debug build though):
Before:
After:
/cc @elsid  @psi29a
=> Avoid reallocs of temp vectors

DebugUtils/CMakeLists.txt, Detour/CMakeLists.txt, DetourCrowd/CMakeLists.txt, DetourTileCache/CMakeLists.txt, Recast/CMakeLists.txt
These files are not generated on Linux that leads to an error:
```
CMake Error at DebugUtils/cmake_install.cmake:60 (file):
file INSTALL cannot find
"/home/elsid/dev/recastnavigation/build/gcc/debug/DebugUtils/DebugUtils-d.pdb":
No such file or directory.
Call Stack (most recent call first):
cmake_install.cmake:47 (include)
```
=> Install .pdb files only on windows

Recast/Include/RecastAlloc.h, RecastDemo/Source/main.cpp
- Set SDL hints to always use OpenGL render driver (instead of Metal render driver by default)
- Compile error fix in Xcode 13 (replaced <RecastAssert.h> to "RecastAssert.h")
=> Fixed RecastDemo crash in macOS 10.11+

DetourTileCache/Source/DetourTileCacheBuilder.cpp, Recast/Source/RecastMesh.cpp
Was causing o3de to not build since it had -Werror and -Wunused-but-set-variable
=> -Wunused-but-set-variable flagged variables removed

Detour/Include/DetourNavMesh.h
Thanks to @pineappleKID for pointing this out! https://github.com/recastnavigation/recastnavigation/issues/535
=> Updated array size in docstring for dtMeshTile::verts

Detour/Include/DetourCommon.h
In Detour/Include/DetourCommon.h:322
`/// @return The dot product on the xz-plane.`
The return value should be the perp dot product rather than the dot product.
=> Correction the comment of dtVperp2D

Recast/Include/RecastAlloc.h
Fixes these warnings triggered every time when `RecastAlloc.h` include is used (encountered in OpenMW):
```
/recastnavigation/Recast/Include/RecastAlloc.h:115:59: warning: extra «;» after in-class function definition [-Wextra-semi]
115 |         rcVectorBase() : m_size(0), m_cap(0), m_data(0) {};
|                                                           ^
|                                                           -
/recastnavigation/Recast/Include/RecastAlloc.h:145:79: warning: extra «;» after in-class function definition [-Wextra-semi]
145 |         const T& back() const { rcAssert(m_size); return m_data[m_size - 1]; };
|                                                                               ^
|                                                                               - …
```
=> Fix -Wextra-semi GCC warnings by removing redundant semicolons

.gitignore
Xcode generates debug symbols in a folder under `Bin/` which isn't being properly ignored.
=> Ignore generated dSYM debug symbols archive on mac

RecastDemo/premake5.lua
The premake script generates some deprecation warnings when generating with premake5:
- "configuration" has been deprecated in favor of "filter"
- "solution" was renamed to "workspace"
=> Fix deprecation warnings when using premake5

RecastDemo/Source/main.cpp
Having two GL contexts causes rendering problems on Ubuntu.  
Fixes #521
=> Don't explicitly create a GL context since SDL_CreateWindowAndRenderer does it internally.

RecastDemo/premake5.lua
Based on SgtVincent's suggestion here: https://github.com/recastnavigation/recastnavigation/issues/497#issuecomment-1293318731
Demotes the warning from an error (due to warnings-as-errors) back to a warning.
Fixes #497
=> Disable class-memaccess error to fix builds on Ubuntu with newer versions of GCC

RecastDemo/premake5.lua
The warnings we were disabling only exist in gcc, so building with clang was throwing errors about unknown warning flags.
Also removes the hard-coded filter on the `gmake` premake target, since it's deprecated in favor of `gmake2` and the cases we're filtering don't care which it's using.  We really just need to filter on gcc.
=> Fix the linux build when building with clang

README.md, RecastDemo/Bin/.gitignore, RecastDemo/premake5.lua
Moved the default expected `SDL2.framework` path to `RecastDemo/Bin` on macOS.
This makes the default xcode project generated by premake work out of the box, (no need to fix it up after it's generated) and is generally an easier workflow for mac users.  Especially those who don't have permissions to modify /Library/Frameworks/
Updated the installation instructions in the README as well.
=> Simplified macOS Build Process

CMakeLists.txt, DebugUtils/CMakeLists.txt, Detour/CMakeLists.txt, DetourCrowd/CMakeLists.txt, DetourTileCache/CMakeLists.txt, Recast/CMakeLists.txt, recastnavigation-config.cmake.in
https://github.com/recastnavigation/recastnavigation/pull/358 has added ALIAS targets, but the title was misleading, ALIAS targets are only for add_subdirectory(), not find_package().
This PR installs a CMake config file containing imported targets of recastnavigation. These targets are consistent with ALIAS one: `RecastNavigation::DebugUtils`, `RecastNavigation::Detour`, `RecastNavigation::DetourCrowd`, `RecastNavigation::DetourTileCache`, `RecastNavigation::Recast`.
Thus, one can find an installation of recastnavigation and link targets, for example:
```cmake
find_package(recastnavigation REQUIRED)
target_link_libraries(foo PRIVATE RecastNavigation::Recast RecastNavigation::Detour)
```
```
mdkir build & cd build
cmake .. -DCMAKE_PREFIX_PATH=<path/to/recastnavigation/install/dir>
```
(it …
=> Install CMake config file to allow find_package()

Recast/Include/Recast.h, Recast/Source/RecastRasterization.cpp
Mostly just improving variable names for clarity.
Removed a redundant base-case check in AddSpan that resulted in a small but measurable perf improvement due to removing a branch.  Also tightened up the bounding box overlap check so it early-outs faster, which also has a small perf improvement to rasterization times.
Updated docstrings for user-facing functions.
=> Cleanup Rasterization Code

Recast/Include/Recast.h, Recast/Include/RecastAlloc.h, Recast/Include/RecastAssert.h, Recast/Source/Recast.cpp, Recast/Source/RecastAlloc.cpp, Recast/Source/RecastAssert.cpp, Recast/Source/RecastFilter.cpp, Recast/Source/RecastRasterization.cpp
Zero functionality changes.  Just formatting changes, local var and parameter name changes, consolidating doc comments and fixing some rule-of-three violations.
Also added a constructor and destructor to rcPolyMeshDetail, since rcAllocPolyMeshDetail and rcFreePolyMeshDetail indicate these can't be trivially constructed or destructed safely like other POD types.
=> More Recast code cleanup

DebugUtils/Source/DebugDraw.cpp, DebugUtils/Source/RecastDebugDraw.cpp, DebugUtils/Source/RecastDump.cpp, DetourCrowd/Source/DetourCrowd.cpp, Recast/Source/Recast.cpp, Recast/Source/RecastArea.cpp, Recast/Source/RecastContour.cpp, Recast/Source/RecastLayers.cpp, Recast/Source/RecastMesh.cpp, Recast/Source/RecastMeshDetail.cpp, Recast/Source/RecastRasterization.cpp, Recast/Source/RecastRegion.cpp, RecastDemo/Source/ConvexVolumeTool.cpp, RecastDemo/Source/CrowdTool.cpp, RecastDemo/Source/InputGeom.cpp, RecastDemo/Source/MeshLoaderObj.cpp, RecastDemo/Source/NavMeshPruneTool.cpp, RecastDemo/Source/NavMeshTesterTool.cpp, RecastDemo/Source/OffMeshConnectionTool.cpp, RecastDemo/Source/Sample.cpp, RecastDemo/Source/SampleInterfaces.cpp, RecastDemo/Source/Sample_Debug.cpp, RecastDemo/Source/Sample_SoloMesh.cpp, RecastDemo/Source/Sample_TempObstacles.cpp, RecastDemo/Source/Sample_TileMesh.cpp, RecastDemo/Source/imgui.cpp, RecastDemo/Source/imguiRenderGL.cpp, RecastDemo/Source/main.cpp
Since none of the `M_` prefixed constants are used anywhere in the code, this is unnecessary.  It's also Windows-specific, so these non-standard defines shouldn't be used anyway.
Ref: https://learn.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-170
=> Removed _USE_MATH_DEFINES directive

DetourTileCache/Source/DetourTileCacheBuilder.cpp
Fix for reading data out of bounds in tile cache builder in removeVertex.
While removing a vertex data is read from i+1 index from mesh.verts, which becomes out of bound for the last vertex, which we shouldn't copy over in this case.
=> Fix for out of bounds read in tile cache builder.

.github/workflows/Docs.yaml
Build and deploys doxygen docs to a gh-pages branch so they can be hosted in GitHub pages.
=> Gh pages deploy workflow

DebugUtils/CMakeLists.txt, Detour/CMakeLists.txt, DetourCrowd/CMakeLists.txt, DetourTileCache/CMakeLists.txt, Recast/CMakeLists.txt
PDBs are not necessarily generated, even in Debug configuration. For example, if the CXX_FLAGS are set to /Z7, debug symbols are embedded, and so the PDBs are not generated. This prevents installing from failing by marking these PDBs as optional.
Fix #610
=> Make installing PDBs optional.

Detour/Source/DetourCommon.cpp
It's only used to detect if the segment is parallel to the polygon edge in question, and if so, skip actually doing the intersection test.  This sets the epsilon to 1e-6, which is about 10x the machine epsilon for 32bit floats, so it's low enough to not give false positives but it's large enough to correctly detect segments and polygon edges that are extremely close to parallel.
Fixes #607
=> Increase epsilon in detour common segment polygon intersection test

Detour/Include/DetourMath.h
Recast and Detour avoid STL and adhere to the C++03 standard to maximize compatibility.  `std::infinite` [was added in C++11](https://en.cppreference.com/w/cpp/numeric/math/isfinite) as a STD-namespaced version of the C `infinite` function in `math.h`.
=> Removed STL function from Detour

Recast/Source/RecastLayers.cpp
It makes possible for a project integrating Recast to set custom values via CXXFLAGS while remaining build system agnostic.
Type checking is kept.
This is an alternative implementation for:
- https://github.com/recastnavigation/recastnavigation/pull/621
Here is an example of how a project integrating Recast may customize `RC_MAX_LAYERS` once this patch is merged. In this example the build-system specific code is entirely externalized, keeping the patch on Recast side small and unlikely to require any maintenance in the future:
- https://github.com/Unvanquished/Unvanquished/pull/2620
This also means that once this PR is merged a third-party project will start relying on this feature and then this feature will not be orphan. This wanted feature fulfills an actual need and merging it …
=> RecastLayers: set RC_MAX_LAYERS and RC_MAX_NEIS as optional defines

Recast/Include/Recast.h, Recast/Source/Recast.cpp, Recast/Source/RecastContour.cpp, Recast/Source/RecastLayers.cpp, Recast/Source/RecastMesh.cpp
Marks some functions which use inputs as const, but that are not marked const.
These functions do not modify their inputs so they should be marked as const to avoid confusion about ownership.
This change does technically modify the public API, but for C++ code at least no uses should change.
=> Mark input data structures as const.

CMakeLists.txt, Detour/CMakeLists.txt
Previously, setting this option required either enabling this option by modifying the source, or doing some CMake hacking to inject the variables. Now this is a convenient option.
=> Add a CMake option to enable 64bit dtPolyRefs for Detour.

Recast/Source/RecastFilter.cpp
The function comment mentions that heights LESS THAN the walkable height will be marked unwalkable. The previous implementation filtered out heights with exactly walkable height space.
=> Fix spans being filtered even if they have just enough clearance.

RecastDemo/Source/NavMeshTesterTool.cpp
In the function dtMergeCorridorStartMoved is re-implemented in NavMeshTesterTool.cpp as fixupCorridor. 
I removed fixupCorridor and replaced with dtMergeCorridorStartMoved.
Fixes #634
=> Removed fixupCorridor and replaced with dtMergeCorridorStartMoved

Tests/Contrib/catch2/catch_all.hpp, Tests/Contrib/catch2/catch_amalgamated.cpp
To get `RangeEquals` matcher making code for matching arrays simpler.
* Files are copied from https://github.com/catchorg/Catch2/releases/tag/v3.4.0.
* `catch_amalgamated.hpp` is renamed to `catch_all.hpp` to match existing file.
=> Update catch to v3.4.0

Recast/Include/Recast.h, Recast/Source/RecastArea.cpp, RecastDemo/Source/Sample_SoloMesh.cpp
This should be a non-functional change apart from one bug I found in `rcOffsetPoly` where [a call to normalize a vector](https://github.com/recastnavigation/recastnavigation/blob/6dc1667f580357e8a2154c28b7867bea7e8ad3a7/Recast/Source/RecastArea.cpp#L489) was dividing it by the squared magnitude rather than the magnitude.
=> Improved variable naming in RecastArea.cpp

DetourCrowd/Source/DetourPathCorridor.cpp
In the function dtPathCorridor::setCorridor
```
dtAssert(npath < m_maxPath);
```
the assertion failure caused a crash on our server.
After analyzing the source code of this file, it was found that the value assigned to m_npath was used as a size rather than an index, and all the places where it was used would not lead to direct access.
in function dtCrowd::updateMoveRequest
```
// Make space for the old path.
if ((npath-1)+nres > m_maxPathResult)
nres = m_maxPathResult - (npath-1);
memmove(res+npath-1, res, sizeof(dtPolyRef)*nres);
// Copy old path in the beginning.
memcpy(res, path, sizeof(dtPolyRef)*(npath-1));
nres += npath-1;
```
there is a possibility of `nres == m_maxPathResult`, so this value is normal.
If there is any misunderstanding, please correct me. Thank you.
=> fix invalid assert dtAssert(npath < m_maxPath)

Detour/Include/DetourAssert.h, Detour/Source/DetourAssert.cpp, Integration.md, README.md, Recast/Include/RecastAssert.h, Recast/Source/RecastAssert.cpp, RecastDemo/premake5.lua
This gives explicit control to users over when recast asserts are enabled or disabled.  This is useful when users wish to disable asserts in debug mode or enable them in release mode.  e.g. it's common to compile game code in debug alongside third party code in release.
Also moved integration instructions to Integration.md and added descriptions for all the current preprocessor definitions.
=> Changed asserts to be explicitly disabled with RC_DISABLE_ASSERTS rather than using NDEBUG

Recast/Source/RecastMeshDetail.cpp
Instead of using a distance check which can fail at large magnitudes due to low precision we can check whether the edges are actually on the hull.
Fix #394
Fix #656
According to [past me](https://github.com/recastnavigation/recastnavigation/issues/394#issuecomment-779895359) I've verified that this gives the same result on our test meshes as the existing distance based approach.
=> Make detail mesh edge detection more robust

DetourCrowd/Source/DetourPathCorridor.cpp, RecastDemo/premake5.lua, Tests/CMakeLists.txt, Tests/DetourCrowd/Tests_DetourPathCorridor.cpp
`size` can become negative if `req > maxPath`. This may happen when `visited` buffer is larger than `path` buffer.
Add tests to cover different use cases of the function including `Should add visited points not present in path up to the path capacity` to cover the fix.
List tests files explicitly. When new file is added CMake does not add it to the already generated list if GLOB is used.
Update catch to `v3.3.2` to get `RangeEquals` matcher making code for matching arrays simpler.
=> Fix out of bounds access in dtMergeCorridorStartMoved and add tests

CMakeLists.txt
The concatenation approach results in paths like `libdir=${exec_prefix}//nix/store/...-recastnavigation-1.6.0/lib`
=> CMake: .pc: let GNUInstallDirs generate the paths

Detour/Include/DetourNavMeshBuilder.h, Detour/Source/DetourNavMeshBuilder.cpp, DetourTileCache/Include/DetourTileCacheBuilder.h
fix same typo 6 times in the comment section of 3 `Detour` related files.
=> [Detour] Fix 6 typos in the comments [ci skip]

.github/workflows/Build.yaml, Detour/Include/DetourMath.h, DetourTileCache/Source/DetourTileCacheBuilder.cpp, RecastDemo/premake5.lua
Fast math is not required, but it speeds up some calculations at the expense of accuracy.  There are some functions like dtMathIsfinite that use floating point functions that become undefined behavior when compiled with fast-math, so we need to conditionally short-circuit these functions when compiled with that flag.
`-Wnan-infinity-disabled` was added in Clang 18 and is complaining about this `isfinite` call in `dtMathIsfinite`.  
This also sets the linux runner explicitly to Ubuntu 24.04, since `ubuntu-latest` defaults to 22.04 for some reason.  This also updates gcc and clang to the latest versions in apt and logs their version to the run output.
Finally, this also removes some unused code that was throwing a warning (and thus an error) on newer compiler versions.
=> Disable calls to isfinite when compiling with -ffast-math

CMakeLists.txt, Detour/CMakeLists.txt, Recast/CMakeLists.txt
Before this change asserts are enabled by default for CMake builds. This impacts performance. Add option to enable or disable asserts with default value depending on the build config. By default enable for Debug builds and disable for everything else.
=> Support enabling and disabling asserts for CMake builds

.github/workflows/Tests.yaml
Since we need to build with clang 18 and ubuntu-latest is still set to 22.04 which uses clang 14.
=> Use newer clang and ubuntu version when building linux tests project

RecastDemo/Source/main.cpp
- Add SDL_WINDOW_RESIZABLE flag to enable window resizing
- Handle SDL_WINDOWEVENT_RESIZED event to update window dimensions
- Update OpenGL viewport and projection matrix when window is resized
This change allows users to resize the application window while maintaining proper aspect ratio and rendering.
=> feat: add window resizing support

.github/workflows/Docs.yaml
Since ubuntu-latest is using 22.04, and the version of doxygen it uses is generating some incorrect headers.
=> Explicitly specify Ubuntu 24.04 rather than ubuntu-latest

CHANGELOG.md
There's a bug in doxygen's markdown html generator when specifying header text that's just link text.  This is fixed in newer versions of doxygen, but the ubuntu images in github actions runners don't have a new enough version to work around this.  Instead, just write out the html explicitly for now.
=> Explicitly use html tags in Changelog to work around bug in doxygen

Recast/Include/RecastAssert.h, Recast/Source/RecastAssert.cpp
Otherwise, client code that calls these custom assertion failure callback registration functions will break when disabling asserts.
=> Don't remove custom assert failure registering code when disabling assertions

DetourTileCache/Source/DetourTileCacheBuilder.cpp, Recast/Source/RecastContour.cpp, Recast/Source/RecastMesh.cpp
The xorb function just gets compiled to an xor instruction in -O3, so this is just unnecessary pessimistic code.
https://godbolt.org/z/o5TGjsx6T
=> Replace xorb with xor operator

Detour/Source/DetourNavMeshQuery.cpp
If an underlying `dtNavMesh` is sufficiently low quality, then there is a chance that `raycast()` can get stuck in an infinite loop (see https://github.com/recastnavigation/recastnavigation/issues/436). This is also the case I found earlier today in my own codebase.
In the linked issue, they mention their loop looks like: `A -> B -> C -> A` for polyRefs. In my case, it's flipping between `A -> B -> A`
In this section:
https://github.com/recastnavigation/recastnavigation/blob/main/Detour/Source/DetourNavMeshQuery.cpp#L2540-L2544
We determine that we've reached the end of the buffer, but we never report failure or even a partial result. This PR does that.
This block could be moved up, or it could also be changed to `DT_FAILURE`
It fixes the issue in my codebase.
Fixes …
=> Add exit condition to raycast() if DT_BUFFER_TOO_SMALL
